---
name: "Scheduled Release"

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  generate-build-matrix:
    name: Generate matrix for building images
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.fetch.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Generate Token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Fetch new app versions
        id: fetch
        run: ./.github/scripts/fetch.sh
        env:
          TOKEN: "${{ steps.generate-token.outputs.token }}"

  images-build:
    uses: kilip/containers/.github/workflows/action-image-build.yaml@main
    if: needs.generate-build-matrix.outputs.matrix != '[]'
    needs: ["generate-build-matrix"]
    with:
      imagesToBuild: "${{ needs.generate-build-matrix.outputs.matrix }}"
      pushImages: "true"
      updateMetadata: "true"
      sendNotification: "true"
    secrets: inherit
